// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hrypqlffvkqirzileboa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhyeXBxbGZmdmtxaXJ6aWxlYm9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNTk2OTEsImV4cCI6MjA1OTgzNTY5MX0.ansFnQF7Oqf0XYpmjsGJYoV1DCGKwMKt_xA73K8HVa4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);